-- Simple test for logger module - mock print to avoid complex setup
local logger = require("logger")

describe("Logger module", function()
  it("should have all required functions", function()
    assert.is_function(logger.info)
    assert.is_function(logger.step)
    assert.is_function(logger.done)
    assert.is_function(logger.warn)
    assert.is_function(logger.fail)
    assert.is_function(logger.pack)
    assert.is_function(logger.find)
    assert.is_function(logger.tool)
    assert.is_function(logger.hint)
  end)

  it("should not error when calling logging functions", function()
    assert.has_no.errors(function() logger.info("test") end)
    assert.has_no.errors(function() logger.step("test") end)
    assert.has_no.errors(function() logger.done("test") end)
    assert.has_no.errors(function() logger.warn("test") end)
    assert.has_no.errors(function() logger.fail("test") end)
    assert.has_no.errors(function() logger.pack("test") end)
    assert.has_no.errors(function() logger.find("test") end)
    assert.has_no.errors(function() logger.tool("test") end)
    assert.has_no.errors(function() logger.hint("test") end)
  end)
end)